import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long Q;
        Q = sc.nextLong();
        double[] X = new double[(int)(Q)];
        double[] Y = new double[(int)(Q)];
        double[] Z = new double[(int)(Q)];
        long[] T = new long[(int)(Q)];
        for(int i = 0 ; i < Q ; i++){
            X[i] = sc.nextDouble();
            Y[i] = sc.nextDouble();
            Z[i] = sc.nextDouble();
            T[i] = sc.nextLong();
        }
        solve(Q, X, Y, Z, T);
    }

    static void solve(long Q, double[] X, double[] Y, double[] Z, long[] T){

    }
}
