import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        String[] c = new String[(int)(1)];
        for(int i = 0 ; i < 1 ; i++){
            c[i] = sc.next();
        }
        solve(N, c);
    }

    static void solve(long N, String[] c){

    }
}
