import java.io.*;
import java.util.*;

class Main {
    static final String YES = "Yes";
    static final String NO = "No";

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long[] x = new long[(int)(4)];
        long[] y = new long[(int)(4)];
        for(int i = 0 ; i < 4 ; i++){
            x[i] = sc.nextLong();
            y[i] = sc.nextLong();
        }
        solve(x, y);
    }

    static void solve(long[] x, long[] y){

    }
}
