import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long[] x = new long[(int)(2)];
        long[] y = new long[(int)(2)];
        long[] r = new long[(int)(2)];
        for(int i = 0 ; i < 2 ; i++){
            x[i] = sc.nextLong();
            y[i] = sc.nextLong();
            r[i] = sc.nextLong();
        }
        solve(x, y, r);
    }

    static void solve(long[] x, long[] y, long[] r){

    }
}
