import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long a_x;
        a_x = sc.nextLong();
        long a_y;
        a_y = sc.nextLong();
        long b_x;
        b_x = sc.nextLong();
        long b_y;
        b_y = sc.nextLong();
        long c_x;
        c_x = sc.nextLong();
        long c_y;
        c_y = sc.nextLong();
        solve(a_x, a_y, b_x, b_y, c_x, c_y);
    }

    static void solve(long a_x, long a_y, long b_x, long b_y, long c_x, long c_y){

    }
}
